### ISSUE TITLE
Add relational operation that accesses underlying tables

### ISSUE THREAD

**Issue by ghost** [graemerocher/oracle-jsonview-demo-app#1]
Add an operation that accesses the underlying tables to demonstrate the duality view.

This could be any REST operation.

For example, to create a new row in the STUDENT_CLASSES table (so that a student is enrolled in a class).

This should not use a Document operation, but instead a Relational operation.

**Comment by graemerocher** [comment]
I altered the create operation to demonstrate this https://github.com/graemerocher/oracle-jsonview-demo-app/commit/4e6a9c20889d8938269a957338938c3ccff1185a
